export const config = {
  offer_id: "2103020895",
  status: 1,
  status_text: "Offered",
  currency: "BDT",
  creation_date: "2023-01-15T02:34:35Z",
  expiration_date: "2023-01-15T02:49:35Z",
  remaining_duration: 814841,
  current_tier_id: "",
  next_tier_id: "bronze",
  amount_to_reach_next_tier: 250,
  joker_fee: null,
  joker_commission_base: null,
  joker_voucher_code: "",
  tiers: [
    { tier_id: "bronze", mov: 250, discount_amount: 65 },
    { tier_id: "silver", mov: 350, discount_amount: 105 },
    { tier_id: "gold", mov: 540, discount_amount: 190 },
  ],
  items: [
    {
      reservation_code: "14084271014",
      is_last_promotion: false,
      status: 0,
      status_text: "Reserved",
      rank: 1,
      vendor: {
        code: "t3aq",
        name: "Nobabi Voj Restaurant \u0026 Catering Service",
        city: "Dhaka",
        details: {
          id: 13113,
          is_active: true,
          code: "t3aq",
          name: "Nobabi Voj Restaurant \u0026 Catering Service",
          url_key: "nobabi-voj-restaurant-and-catering-service",
          vendor_hero_listing_image:
            "https://images.deliveryhero.io/image/fd-bd/LH/t3aq-listing.jpg",
          rating: 4,
          review_number: 2959,
          review_with_comment_number: 0,
          primary_cuisine: {
            id: 195,
            name: "Bangladeshi",
            url_key: "bangladeshi",
          },
          cuisines: [
            { id: 122, name: "Snacks", url_key: "snacks" },
            { id: 243, name: "Curry", url_key: "curry" },
            { id: 107, name: "Soups", url_key: "soups" },
            { id: 118, name: "Fish", url_key: "fish" },
            { id: 82, name: "Seafood", url_key: "seafood" },
            { id: 74, name: "Chinese", url_key: "chinese" },
            { id: 195, name: "Bangladeshi", url_key: "bangladeshi" },
            { id: 75, name: "Asian", url_key: "asian" },
            { id: 86, name: "Fast Food", url_key: "fast-food" },
          ],
          food_characteristics: [],
          minimum_order_amount: 0,
          delivery_fee_type: "amount",
          minimum_delivery_fee: 0,
          minimum_delivery_time: 30,
          timezone: "Asia/Dhaka",
          budget: 3,
        },
      },
    },
    {
      reservation_code: "14084271015",
      is_last_promotion: false,
      status: 0,
      status_text: "Reserved",
      rank: 2,
      vendor: {
        code: "ks9w",
        name: "Jhawbon Classic Restaurant",
        city: "Dhaka",
        details: {
          id: 33504,
          is_active: true,
          code: "ks9w",
          name: "Jhawbon Classic Restaurant",
          url_key: "jhawbon-classic-restaurant-ks9w",
          vendor_hero_listing_image:
            "https://images.deliveryhero.io/image/fd-bd/LH/ks9w-listing.jpg",
          rating: 3.7,
          review_number: 399,
          review_with_comment_number: 0,
          primary_cuisine: {
            id: 195,
            name: "Bangladeshi",
            url_key: "bangladeshi",
          },
          cuisines: [
            { id: 243, name: "Curry", url_key: "curry" },
            { id: 123, name: "Rice Dishes", url_key: "rice-dishes" },
            { id: 195, name: "Bangladeshi", url_key: "bangladeshi" },
            { id: 75, name: "Asian", url_key: "asian" },
          ],
          food_characteristics: [],
          minimum_order_amount: 0,
          delivery_fee_type: "amount",
          minimum_delivery_fee: 0,
          minimum_delivery_time: 25,
          timezone: "Asia/Dhaka",
          budget: 3,
        },
      },
    },
    {
      reservation_code: "14084271016",
      is_last_promotion: false,
      status: 0,
      status_text: "Reserved",
      rank: 3,
      vendor: {
        code: "mm8d",
        name: "Kismot Biryani \u0026 Restaurant",
        city: "Dhaka",
        details: {
          id: 32099,
          is_active: true,
          code: "mm8d",
          name: "Kismot Biryani \u0026 Restaurant",
          url_key: "kismot-biryani-and-restaurant",
          vendor_hero_listing_image:
            "https://images.deliveryhero.io/image/fd-bd/LH/mm8d-listing.jpg",
          rating: 3.8,
          review_number: 553,
          review_with_comment_number: 0,
          primary_cuisine: {
            id: 195,
            name: "Bangladeshi",
            url_key: "bangladeshi",
          },
          cuisines: [
            { id: 123, name: "Rice Dishes", url_key: "rice-dishes" },
            { id: 118, name: "Fish", url_key: "fish" },
            { id: 82, name: "Seafood", url_key: "seafood" },
            { id: 94, name: "Vegetarian", url_key: "vegetarian" },
            { id: 195, name: "Bangladeshi", url_key: "bangladeshi" },
            { id: 75, name: "Asian", url_key: "asian" },
          ],
          food_characteristics: [],
          minimum_order_amount: 0,
          delivery_fee_type: "amount",
          minimum_delivery_fee: 0,
          minimum_delivery_time: 35,
          timezone: "Asia/Dhaka",
          budget: 2,
        },
      },
    },
    {
      reservation_code: "14084271017",
      is_last_promotion: false,
      status: 0,
      status_text: "Reserved",
      rank: 4,
      vendor: {
        code: "z995",
        name: "New Bismillah Hotel \u0026 Restaurant - (Gulshan-1)",
        city: "Dhaka",
        details: {
          id: 45820,
          is_active: true,
          code: "z995",
          name: "New Bismillah Hotel \u0026 Restaurant - (Gulshan-1)",
          url_key: "new-bismillah-hotel-and-restaurant-gulshan-1",
          vendor_hero_listing_image:
            "https://images.deliveryhero.io/image/fd-bd/LH/z995-listing.jpg",
          rating: 3.5,
          review_number: 623,
          review_with_comment_number: 0,
          primary_cuisine: {
            id: 195,
            name: "Bangladeshi",
            url_key: "bangladeshi",
          },
          cuisines: [
            { id: 122, name: "Snacks", url_key: "snacks" },
            { id: 243, name: "Curry", url_key: "curry" },
            { id: 123, name: "Rice Dishes", url_key: "rice-dishes" },
            { id: 195, name: "Bangladeshi", url_key: "bangladeshi" },
            { id: 75, name: "Asian", url_key: "asian" },
          ],
          food_characteristics: [],
          minimum_order_amount: 0,
          delivery_fee_type: "amount",
          minimum_delivery_fee: 0,
          minimum_delivery_time: 30,
          timezone: "Asia/Dhaka",
          budget: 1,
        },
      },
    },
    {
      reservation_code: "14084271018",
      is_last_promotion: false,
      status: 0,
      status_text: "Reserved",
      rank: 5,
      vendor: {
        code: "ynvj",
        name: "Hossain Biryani House",
        city: "Dhaka",
        details: {
          id: 35883,
          is_active: true,
          code: "ynvj",
          name: "Hossain Biryani House",
          url_key: "hossain-biryani-house",
          vendor_hero_listing_image:
            "https://images.deliveryhero.io/image/fd-bd/LH/ynvj-listing.jpg",
          rating: 3,
          review_number: 133,
          review_with_comment_number: 0,
          primary_cuisine: {
            id: 195,
            name: "Bangladeshi",
            url_key: "bangladeshi",
          },
          cuisines: [
            { id: 132, name: "Kebab", url_key: "kebab" },
            { id: 123, name: "Rice Dishes", url_key: "rice-dishes" },
            { id: 118, name: "Fish", url_key: "fish" },
            { id: 82, name: "Seafood", url_key: "seafood" },
            { id: 95, name: "Meat", url_key: "meat" },
            { id: 195, name: "Bangladeshi", url_key: "bangladeshi" },
            { id: 75, name: "Asian", url_key: "asian" },
          ],
          food_characteristics: [],
          minimum_order_amount: 0,
          delivery_fee_type: "amount",
          minimum_delivery_fee: 0,
          minimum_delivery_time: 25,
          timezone: "Asia/Dhaka",
          budget: 3,
        },
      },
    },
    {
      reservation_code: "14084271019",
      is_last_promotion: false,
      status: 0,
      status_text: "Reserved",
      rank: 6,
      vendor: {
        code: "inef",
        name: "Prezzie - Gulshan",
        city: "Dhaka",
        details: {
          id: 56802,
          is_active: true,
          code: "inef",
          name: "Prezzie - Gulshan",
          url_key: "prezzie-gulshan",
          vendor_hero_listing_image:
            "https://images.deliveryhero.io/image/fd-bd/LH/inef-listing.jpg",
          rating: 3.6,
          review_number: 52,
          review_with_comment_number: 0,
          primary_cuisine: { id: 147, name: "Beverage", url_key: "beverage" },
          cuisines: [
            { id: 147, name: "Beverage", url_key: "beverage" },
            { id: 90, name: "Cafe", url_key: "cafe" },
            { id: 71, name: "Sandwiches", url_key: "sandwiches" },
            { id: 84, name: "Dessert", url_key: "dessert" },
          ],
          food_characteristics: [],
          minimum_order_amount: 0,
          delivery_fee_type: "amount",
          minimum_delivery_fee: 0,
          minimum_delivery_time: 35,
          timezone: "Asia/Dhaka",
          budget: 2,
        },
      },
    },
    {
      reservation_code: "14084271020",
      is_last_promotion: false,
      status: 0,
      status_text: "Reserved",
      rank: 7,
      vendor: {
        code: "s7qf",
        name: "King's Kabab And Restaurant - Niketon",
        city: "Dhaka",
        details: {
          id: 2519,
          is_active: true,
          code: "s7qf",
          name: "King's Kabab And Restaurant - Niketon",
          url_key: "kings-kabab-and-restaurant-niketon",
          vendor_hero_listing_image:
            "https://images.deliveryhero.io/image/fd-bd/LH/s7qf-listing.jpg",
          rating: 3.9,
          review_number: 5249,
          review_with_comment_number: 0,
          primary_cuisine: { id: 132, name: "Kebab", url_key: "kebab" },
          cuisines: [
            { id: 132, name: "Kebab", url_key: "kebab" },
            { id: 122, name: "Snacks", url_key: "snacks" },
            { id: 123, name: "Rice Dishes", url_key: "rice-dishes" },
            { id: 95, name: "Meat", url_key: "meat" },
          ],
          food_characteristics: [],
          minimum_order_amount: 0,
          delivery_fee_type: "amount",
          minimum_delivery_fee: 0,
          minimum_delivery_time: 25,
          timezone: "Asia/Dhaka",
          budget: 2,
        },
      },
    },
    {
      reservation_code: "14084271021",
      is_last_promotion: false,
      status: 0,
      status_text: "Reserved",
      rank: 8,
      vendor: {
        code: "e0je",
        name: "Muslim Sweets \u0026 Bakery",
        city: "Dhaka",
        details: {
          id: 61882,
          is_active: true,
          code: "e0je",
          name: "Muslim Sweets \u0026 Bakery",
          url_key: "muslim-sweets-and-bakery-e0je",
          vendor_hero_listing_image:
            "https://images.deliveryhero.io/image/fd-bd/LH/e0je-listing.jpg",
          rating: 2.9,
          review_number: 8,
          review_with_comment_number: 0,
          primary_cuisine: { id: 84, name: "Dessert", url_key: "dessert" },
          cuisines: [{ id: 84, name: "Dessert", url_key: "dessert" }],
          food_characteristics: [],
          minimum_order_amount: 0,
          delivery_fee_type: "amount",
          minimum_delivery_fee: 0,
          minimum_delivery_time: 30,
          timezone: "Asia/Dhaka",
          budget: 3,
        },
      },
    },
  ],
};
